package com.newbieeming.hookhyper.core.hook

import android.content.SharedPreferences
import io.github.libxposed.api.XposedInterface
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import java.lang.reflect.Proxy

class ModularHookerTest {
    private var preferenceReads = 0
    private var enabled = false
    private val hooker = object : ModularHooker("test", "target.package") {}

    @Before
    fun reset() {
        HookRegistry.calls = 0
    }

    @Test
    fun skipsUnrelatedPackages() {
        enabled = true
        hooker.onHook(context("other.package"))
        assertEquals(0, preferenceReads)
        assertEquals(0, HookRegistry.calls)
    }

    @Test
    fun skipsDisabledFeatures() {
        hooker.onHook(context("target.package"))
        assertEquals(1, preferenceReads)
        assertEquals(0, HookRegistry.calls)
    }

    @Test
    fun loadsEnabledFeatures() {
        enabled = true
        hooker.onHook(context("target.package"))
        assertEquals(1, preferenceReads)
        assertEquals(1, HookRegistry.calls)
    }

    private fun context(packageName: String): HookContext {
        val preferences = Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(SharedPreferences::class.java),
        ) { _, method, _ ->
            check(method.name == "getBoolean")
            enabled
        } as SharedPreferences
        val framework = Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(XposedInterface::class.java),
        ) { _, method, _ ->
            check(method.name == "getRemotePreferences")
            preferenceReads++
            preferences
        } as XposedInterface
        return HookContext(framework, packageName, javaClass.classLoader!!)
    }
}

/** Same shape as the feature registry generated by KSP. */
object HookRegistry {
    var calls = 0
    val modules = listOf(object : SubHooker {
        override val preferenceKey = "feature_enabled"

        override fun HookContext.onHook() {
            calls++
        }
    })
}
