package com.newbieeming.hookhyper.ksp

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.WildcardTypeName
import com.squareup.kotlinpoet.asTypeName
import com.squareup.kotlinpoet.ksp.writeTo

private const val ANNOTATION_NAME = "com.newbieeming.hookhyper.core.hook.HookModule"
private const val AGGREGATE_FILE = "hookhyper-registrars.txt"

class HookModuleProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        HookModuleProcessor(environment.codeGenerator, environment.logger)
}

private class HookModuleProcessor(
    private val codeGenerator: com.google.devtools.ksp.processing.CodeGenerator,
    private val logger: com.google.devtools.ksp.processing.KSPLogger,
) : SymbolProcessor {

    private var processed = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()

        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)
        val deferred = mutableListOf<KSAnnotated>()
        val entries = mutableListOf<HookEntry>()

        for (symbol in symbols) {
            if (!symbol.validate()) { deferred += symbol; continue }
            if (symbol !is KSClassDeclaration) {
                logger.error("@HookModule must annotate a class", symbol); continue
            }

            val annotation = symbol.annotations.first {
                it.annotationType.resolve().declaration.qualifiedName?.asString() == ANNOTATION_NAME
            }
            val targetPkg = annotation.arg("packageName") as? String
            val key = annotation.arg("preferenceKey") as? String
            if (targetPkg.isNullOrBlank() || key.isNullOrBlank()) {
                logger.error("@HookModule requires packageName and preferenceKey", symbol); continue
            }

            val fqName = symbol.qualifiedName?.asString()
                ?: run { logger.error("Cannot resolve qualified name", symbol); continue }

            val classPkg = symbol.packageName.asString()
            entries += HookEntry(targetPkg, key, classPkg, ClassName.bestGuess(fqName))
        }

        if (entries.isNotEmpty()) {
            // Feature 模块：生成 HookRegistry + FeatureHooker + FeatureRegistrar
            processed = true
            generateFeatureModule(entries)
        } else {
            // App 模块：读取聚合文件，生成 GeneratedHookEntry
            processed = true
            generateAppEntry()
        }

        return deferred
    }

    private fun com.google.devtools.ksp.symbol.KSAnnotation.arg(name: String): Any? =
        arguments.firstOrNull { it.name?.asString() == name }?.value

    // ── Feature 模块 ──────────────────────────────────────────────

    private fun generateFeatureModule(entries: List<HookEntry>) {
        val genPkg = entries.first().classPkg
        val targetPkg = entries.first().targetPkg

        generateHookRegistry(genPkg, entries)
        generateHooker(genPkg, targetPkg)
        generateRegistrar(genPkg)
    }

    private fun generateHookRegistry(pkg: String, entries: List<HookEntry>) {
        val subHooker = ClassName("com.newbieeming.hookhyper.core.hook", "SubHooker")
        val pairType = Pair::class.asTypeName().parameterizedBy(
            String::class.asTypeName(),
            ClassName("kotlin", "Function0").parameterizedBy(subHooker),
        )
        val listType = List::class.asTypeName().parameterizedBy(pairType)

        val code = CodeBlock.builder().add("listOf(\n").indent()
        for (entry in entries) {
            code.add("%S to { %T() },\n", entry.key, entry.className)
        }
        code.unindent().add(")\n")

        val prop = PropertySpec.builder("modules", listType).initializer(code.build()).build()
        val obj = TypeSpec.objectBuilder("HookRegistry")
            .addKdoc("Auto-generated by @HookModule KSP processor. Do not edit manually.")
            .addProperty(prop)
            .build()

        FileSpec.builder(pkg, "HookRegistry").addType(obj).build()
            .writeTo(codeGenerator, Dependencies(false))
    }

    private fun generateHooker(genPkg: String, targetPkg: String) {
        val modularHooker = ClassName("com.newbieeming.hookhyper.core.hook", "ModularHooker")
        val obj = TypeSpec.objectBuilder("FeatureHooker")
            .superclass(modularHooker)
            .addSuperclassConstructorParameter("%S", "HookHyper")
            .addSuperclassConstructorParameter("%S", targetPkg)
            .addKdoc("Auto-generated. Main hooker for [%L].", targetPkg)
            .build()

        FileSpec.builder(genPkg, "FeatureHooker").addType(obj).build()
            .writeTo(codeGenerator, Dependencies(false))
    }

    private fun generateRegistrar(genPkg: String) {
        val registrarIface = ClassName("com.newbieeming.hookhyper.core.hook", "Registrar")
        val yukiBaseHooker = ClassName("com.highcapable.yukihookapi.hook.entity", "YukiBaseHooker")
        val hookerClass = ClassName(genPkg, "FeatureHooker")

        val obj = TypeSpec.objectBuilder("FeatureRegistrar")
            .addSuperinterface(registrarIface)
            .addFunction(
                FunSpec.builder("hooker")
                    .addModifiers(com.squareup.kotlinpoet.KModifier.OVERRIDE)
                    .returns(yukiBaseHooker)
                    .addStatement("return %T", hookerClass)
                    .build()
            )
            .addKdoc("Auto-generated. Discovered by ServiceLoader at runtime.")
            .build()

        FileSpec.builder(genPkg, "FeatureRegistrar").addType(obj).build()
            .writeTo(codeGenerator, Dependencies(false))

        // 写入聚合文件，供 app 模块读取
        codeGenerator.createNewFile(Dependencies(false), "", AGGREGATE_FILE, "")
            .bufferedWriter().use { it.write("$genPkg.FeatureRegistrar\n") }
    }

    // ── App 模块 ──────────────────────────────────────────────────

    private fun generateAppEntry() {
        val registrars = readAggregationFile()
        if (registrars.isEmpty()) {
            logger.warn("No @HookModule registrars found. Ensure feature modules apply hook.module plugin.")
            return
        }

        val genPkg = "com.newbieeming.hookhyper.hook.gen"
        val registrarIface = ClassName("com.newbieeming.hookhyper.core.hook", "Registrar")

        val listCode = CodeBlock.builder().add("listOf(\n").indent()
        for (fqn in registrars) {
            listCode.add("%T::class.java,\n", ClassName.bestGuess(fqn))
        }
        listCode.unindent().add(")\n")

        val listType = List::class.asTypeName().parameterizedBy(
            Class::class.asTypeName().parameterizedBy(WildcardTypeName.producerOf(registrarIface))
        )

        val registerFun = FunSpec.builder("register")
            .addStatement(
                "com.highcapable.yukihookapi.YukiHookAPI.encase(*registrars.map { it.getDeclaredConstructor().newInstance().hooker() }.toTypedArray())"
            )
            .build()

        val obj = TypeSpec.objectBuilder("GeneratedHookEntry")
            .addKdoc("Auto-generated. Aggregates all feature module hookers.")
            .addProperty(
                PropertySpec.builder("registrars", listType)
                    .initializer(listCode.build())
                    .build()
            )
            .addFunction(registerFun)
            .build()

        FileSpec.builder(genPkg, "GeneratedHookEntry").addType(obj).build()
            .writeTo(codeGenerator, Dependencies(false))
    }

    private fun readAggregationFile(): List<String> {
        // 从 feature 模块所有已生成的变体输出读取。不能把路径固定为 debug，
        // 否则 release 构建无法生成 GeneratedHookEntry。
        val rootDir = System.getProperty("user.dir")
        return listOf("feature/systemui", "feature/settings").flatMap { path ->
            val kspOutputDir = java.io.File(rootDir, "$path/build/generated/ksp")
            kspOutputDir.listFiles()
                .orEmpty()
                .map { variantDir -> java.io.File(variantDir, "resources/$AGGREGATE_FILE") }
                .filter(java.io.File::isFile)
                .flatMap { file -> file.readLines().map(String::trim).filter(String::isNotBlank) }
        }.distinct()
    }
}

private data class HookEntry(
    val targetPkg: String,
    val key: String,
    val classPkg: String,
    val className: ClassName,
)
